config/routes.rb
UserManSys::Application.routes.draw do
  resources :roles

  resources :roles_users

  resources :users_roles

  resources :users

end

app/models/roles_user.rb
class RolesUser < ActiveRecord::Base
  attr_accessible :role_id, :user_id
end

app/controllers/roles_users_controller.rb
class RolesUsersController < ApplicationController
  # GET /roles_users
  # GET /roles_users.json
  def index
    @roles_users = RolesUser.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @roles_users }
    end
  end

  # GET /roles_users/1
  # GET /roles_users/1.json
  def show
    @roles_user = RolesUser.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @roles_user }
    end
  end

  # GET /roles_users/new
  # GET /roles_users/new.json
  def new
    @roles_user = RolesUser.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @roles_user }
    end
  end

  # GET /roles_users/1/edit
  def edit
    @roles_user = RolesUser.find(params[:id])
  end

  # POST /roles_users
  # POST /roles_users.json
  def create
    @roles_user = RolesUser.new(params[:roles_user])

    respond_to do |format|
      if @roles_user.save
        format.html { redirect_to @roles_user, notice: 'Roles user was successfully created.' }
        format.json { render json: @roles_user, status: :created, location: @roles_user }
      else
        format.html { render action: "new" }
        format.json { render json: @roles_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /roles_users/1
  # PUT /roles_users/1.json
  def update
    @roles_user = RolesUser.find(params[:id])

    respond_to do |format|
      if @roles_user.update_attributes(params[:roles_user])
        format.html { redirect_to @roles_user, notice: 'Roles user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @roles_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles_users/1
  # DELETE /roles_users/1.json
  def destroy
    @roles_user = RolesUser.find(params[:id])
    @roles_user.destroy

    respond_to do |format|
      format.html { redirect_to roles_users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/roles_users_helper.rb
module RolesUsersHelper
end

app/views/roles_users/_form.html.erb
<%= form_for(@roles_user) do |f| %>
  <% if @roles_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@roles_user.errors.count, "error") %> prohibited this roles_user from being saved:</h2>

      <ul>
      <% @roles_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :role_id %><br />
    <%= f.number_field :role_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles_users/edit.html.erb
<h1>Editing roles_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @roles_user %> |
<%= link_to 'Back', roles_users_path %>

app/views/roles_users/index.html.erb
<h1>Listing roles_users</h1>

<table>
  <tr>
    <th>Role</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @roles_users.each do |roles_user| %>
  <tr>
    <td><%= roles_user.role_id %></td>
    <td><%= roles_user.user_id %></td>
    <td><%= link_to 'Show', roles_user %></td>
    <td><%= link_to 'Edit', edit_roles_user_path(roles_user) %></td>
    <td><%= link_to 'Destroy', roles_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Roles user', new_roles_user_path %>

app/views/roles_users/new.html.erb
<h1>New roles_user</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_users_path %>

app/views/roles_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Role:</b>
  <%= @roles_user.role_id %>
</p>

<p>
  <b>User:</b>
  <%= @roles_user.user_id %>
</p>


<%= link_to 'Edit', edit_roles_user_path(@roles_user) %> |
<%= link_to 'Back', roles_users_path %>