config/routes.rb
UserManSys::Application.routes.draw do
  resources :roles

  resources :roles_users

  resources :users_roles

  resources :users

end

app/models/users_role.rb
class UsersRole < ActiveRecord::Base
  attr_accessible :role_id, :user_id
end

app/controllers/users_roles_controller.rb
class UsersRolesController < ApplicationController
  # GET /users_roles
  # GET /users_roles.json
  def index
    @users_roles = UsersRole.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users_roles }
    end
  end

  # GET /users_roles/1
  # GET /users_roles/1.json
  def show
    @users_role = UsersRole.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @users_role }
    end
  end

  # GET /users_roles/new
  # GET /users_roles/new.json
  def new
    @users_role = UsersRole.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @users_role }
    end
  end

  # GET /users_roles/1/edit
  def edit
    @users_role = UsersRole.find(params[:id])
  end

  # POST /users_roles
  # POST /users_roles.json
  def create
    @users_role = UsersRole.new(params[:users_role])

    respond_to do |format|
      if @users_role.save
        format.html { redirect_to @users_role, notice: 'Users role was successfully created.' }
        format.json { render json: @users_role, status: :created, location: @users_role }
      else
        format.html { render action: "new" }
        format.json { render json: @users_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users_roles/1
  # PUT /users_roles/1.json
  def update
    @users_role = UsersRole.find(params[:id])

    respond_to do |format|
      if @users_role.update_attributes(params[:users_role])
        format.html { redirect_to @users_role, notice: 'Users role was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @users_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users_roles/1
  # DELETE /users_roles/1.json
  def destroy
    @users_role = UsersRole.find(params[:id])
    @users_role.destroy

    respond_to do |format|
      format.html { redirect_to users_roles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_roles_helper.rb
module UsersRolesHelper
end

app/views/users_roles/_form.html.erb
<%= form_for(@users_role) do |f| %>
  <% if @users_role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@users_role.errors.count, "error") %> prohibited this users_role from being saved:</h2>

      <ul>
      <% @users_role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :role_id %><br />
    <%= f.number_field :role_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users_roles/edit.html.erb
<h1>Editing users_role</h1>

<%= render 'form' %>

<%= link_to 'Show', @users_role %> |
<%= link_to 'Back', users_roles_path %>

app/views/users_roles/index.html.erb
<h1>Listing users_roles</h1>

<table>
  <tr>
    <th>User</th>
    <th>Role</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users_roles.each do |users_role| %>
  <tr>
    <td><%= users_role.user_id %></td>
    <td><%= users_role.role_id %></td>
    <td><%= link_to 'Show', users_role %></td>
    <td><%= link_to 'Edit', edit_users_role_path(users_role) %></td>
    <td><%= link_to 'Destroy', users_role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Users role', new_users_role_path %>

app/views/users_roles/new.html.erb
<h1>New users_role</h1>

<%= render 'form' %>

<%= link_to 'Back', users_roles_path %>

app/views/users_roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @users_role.user_id %>
</p>

<p>
  <b>Role:</b>
  <%= @users_role.role_id %>
</p>


<%= link_to 'Edit', edit_users_role_path(@users_role) %> |
<%= link_to 'Back', users_roles_path %>